# Default values for kiosk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

manager:
  command: 
  - /manager
  args: []
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

apiserver:
  command:
  - /apiserver
  args: []
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

certManager:
  certificate:
    create: true
  issuer:
    create: true

apiService:
  enabled: true

certSecret: webhook-server-cert

serviceAccount:
  name: serviceaccount
  create: true
  clusterRole: cluster-admin

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443
  targetPort: 9443

nodeSelector: {}

tolerations: []

affinity: {}
