apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "kiosk.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ template "kiosk.fullname" . }}"
  labels:
    app: {{ template "kiosk.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "kiosk.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /quota
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: kiosk.sh/account
      operator: Exists
  name: accountquota.kiosk.sh
  rules:
  - apiGroups:
    - "*"
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE
    resources:
    - "*"
    scope: "Namespaced"
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ template "kiosk.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate
  failurePolicy: Fail
  name: config.kiosk.sh
  rules:
  - apiGroups:
    - config.kiosk.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
      - '*'
