apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templates.config.kiosk.sh
spec:
  conversion:
    strategy: None
  group: config.kiosk.sh
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: Cluster
  preserveUnknownFields: true
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
