apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templateinstances.config.kiosk.sh
spec:
  conversion:
    strategy: None
    group: config.kiosk.sh
    names:
      kind: TemplateInstance
      listKind: TemplateInstanceList
      plural: templateinstances
      singular: templateinstance
    scope: Namespaced
    preserveUnknownFields: true
    subresources:
      status: {}
    version: v1alpha1
    versions:
      - name: v1alpha1
        served: true
        storage: true
